### ISSUE TITLE
RM510 service menu access

### ISSUE THREAD

**Issue by katzenberger** [martonmiklos/robomow_rm_510_mainboard_schematic#1]
Hi,
I'm trying to repair a Robomow RM510, and your schematic is a huge help.
My question is, how did you enter into the service menu to test the motors? It ask me to enter a 5 digit password.

Thank you,
Peter

**Comment by martonmiklos** [comment]
Hi @katzenberger 

01210 is the master code.
There is a service manual for the RM series floating online, it could be helpful for your endeavor::
https://www.dropbox.com/s/6xf6s2zh5ikirl9/Robomow%20RM-510%20Service%20manual.pdf?dl=0

**Comment by katzenberger** [comment]
> Hi @katzenberger 
> 
> 01210 is the master code.
> There is a service manual for the RM series floating online, it could be helpful for your endeavor::
> https://www.dropbox.com/s/6xf6s2zh5ikirl9/Robomow%20RM-510%20Service%20manual.pdf?dl=0
> 

Hi,

I checked the code, it worked! Thank you very much!
The service manual is very useful too! Thank you!

Peter

**Comment by martonmiklos** [comment]
> > Hi @katzenberger
> > 01210 is the master code.
> > There is a service manual for the RM series floating online, it could be helpful for your endeavor::
> > https://www.dropbox.com/s/6xf6s2zh5ikirl9/Robomow%20RM-510%20Service%20manual.pdf?dl=0
> 
> Hi,
> 
> I checked the code, it worked! Thank you very much! The service manual is very useful too! Thank you!
> 
> Peter

Glad to hear, good luck with the repair process!

**Comment by katzenberger** [comment]
Hi @martonmiklos!
The attached service manual was a huge help to find the error in my Robomow RM-510. Thank you!

Now, I tried to connect via RJ11 cable to RM toolkit. But it doesn't work. I connected these pins:
RJ11 pin 1 - TTL USB serial GND
RJ11 pin 2 - TTL USB serial Rxd
RJ11 pin 3 - TTL USB serial Txd

(It is an 5V TTL USB-serial PL2303X dongle, but I checked with a CH340G adapter too)

I checked all RJ11 pins with scope, but all RJ11 pins are low in idle. Uart idle is high level in normal cases. Is it an inverted uart signal here?

Thank you,
Peter

**Comment by martonmiklos** [comment]
Hi @katzenberger  I actually built a dongle from an FTDI chip for this purpose:

https://github.com/martonmiklos/robomow_usb_adapter

I did not added any inverter, but if IIRC I have inverted the config in the FTDI EEPROM, but let me check and update the README with it.

**Comment by martonmiklos** [comment]
I have forgot to add one note for the USB dongle: it works with a cross pinout cable (physically straight): 
![kép](https://user-images.githubusercontent.com/1609182/237052287-c97cc8f1-587d-4b28-abed-3bf62dd92400.png)

**Comment by katzenberger** [comment]
Thank you @martonmiklos!

I had to invert the rx/tx lines and it works now!

I have an usb-serial adapter with FT232 chip, but I think it is a fake one, bacause I couldn't flash the eeprom with the FTDI tool.

**Comment by martonmiklos** [comment]
Thanks @katzenberger 
I have updated the README in the USB dongle repo.

**Comment by martonmiklos** [comment]
Hi @katzenberger 
I just came across this repository: 
https://github.com/katzenberger/robomow_rm_toolkit_protocol

I should say a lot of thank you for that!

What was your goal with the reveng?
Have you made some control electronics for your mower?

**Comment by katzenberger** [comment]
Hi @martonmiklos 

I planned a mower monitoring device with ESP32 over wifi for integrating into my home automation system. Monitoring battery percentage, charging parameters, temperatures, etc.
But due to lack of time, it has not been implemented yet.

I couldn't find anything useful libs or commands for controlling the lawnmower via the service port, so I planned to connect the start/stop buttons directly to the ESP32.

**Comment by martonmiklos** [comment]
Many thanks for the answer @katzenberger !

I wanted to drive my robot from ROS, but I ended up with the same conclusion.
I have disassembled the available firmware with IDA, however they not seems to be not handling any extra commands.

Having an IRDA remote emulator + an additional UART for control seems to be the best option for now.

**Comment by katzenberger** [comment]
Hi @martonmiklos!

The IRDA remote emulator also works, but it cannot send mowing start/stop commands. So I have to use the built in scheduler now. But my future plan is starting it from my home assistant/home automation system. (depending on rain or sprinkler system usage, etc.)

**Comment by martonmiklos** [comment]
> The IRDA remote emulator also works, but it cannot send mowing start/stop commands. 

Damn, I have had high hopes to it. 
Is not it working the same way as the older RL models?
You need to press mow button together with an another see this video (timestamp included URL)
https://youtu.be/esK11DtFGDg?t=12

**Comment by katzenberger** [comment]
It is okay, but with the IRDA remote you have to controll the forward/backward left/right directions too. You cannot start the automated mowing process as the physical START button can on the device.

I built an IR emulator, and it worked for me, but I had to controll the mower with the IR remote controller as a RC car. :)

**Comment by martonmiklos** [comment]
Ah okay, I see your point now!
